### ISSUE TITLE
Request older than xx ms, even when it's done immediatly. 

### ISSUE THREAD

**Issue by Erowlin** [heroku/rack-timeout#100]
We encountered a problem on one of our development application. 

We got the error message "Request older than xxx ms", even when the request is done immediatly, by watching the logs in live. 
I believe there is something related with the Chrome browser, because when I open the same request on Safari or Firefox, there is not such problem. It's important to note that the problem seems to be randomly happening, because when there is the bug, we can't go to the page for ~5 / 30 minutes, and after that time it work again. Tried to clean my cache / reboot, and nothing work. 

We are in Ruby 2.2x and Rails 4.2.

**Comment by Erowlin** [comment]
Note that when the rack-timeout print the error in the logs, our puma server show us this message : 
"An unhandled lowlevel error occurred. The application logs may have details.".

**Comment by kch** [comment]
Re the last comment, which version of rack-timeout and puma? They didn't play well with each other until recently, so recent versions are highly recommended.

As for the main issue, it's probably related to wait_timeout. Check out the readme if you'd like to turn it off. Basically if your application server and your web servers do not have their times synchronised, the time difference will impact how we calculate request age. So it makes sense that eventually it fixes itself as ntp corrects the time drift.

**Comment by Erowlin** [comment]
Thank you for your reply. It's been a long time for a startup, and I can't tell you anymore since we switched to Passenger.
