### ISSUE TITLE
Supporting service_timeout as a Proc

### ISSUE THREAD

**Issue by zhuochun** [heroku/rack-timeout#107]
I would like to timeout only at specific endpoints, or specific requests (e.g. GET)

I am thinking about supporting `service_timeout` with a Proc, e.g.

``` ruby
Rack::Timeout.service_timeout = ->(env) do
  if special_case
    false
  else
    15
  end
end
```

Open for discussion on the alternatives.

**Comment by wuputah** [comment]
Closed as duplicate. Please see #9, #56, #64, #67.
