### ISSUE TITLE
syntax error, unexpected tLABEL (SyntaxError)

### ISSUE THREAD

**Issue by nextofsearch** [heroku/rack-timeout#109]
Hi,

I am getting this error with rack-timeout 0.4.0 or higher. This error does not happen with up-to 0.3.2.

ruby 1.9.3-p551 & rails 3.2.22.2

`danolee$ bundle exec rails g capistrano:unicorn_nginx:config
/Users/danolee/.rvm/gems/ruby-1.9.3-p551@rails3.2/gems/rack-timeout-0.4.2/lib/rack/timeout/base.rb:1:in `require_relative': /Users/danolee/.rvm/gems/ruby-1.9.3-p551@rails3.2/gems/rack-timeout-0.4.2/lib/rack/timeout/core.rb:66: syntax error, unexpected tLABEL (SyntaxError)
...nitialize(app, service_timeout:nil, wait_timeout:nil, wait_o...
...                               ^
/Users/danolee/.rvm/gems/ruby-1.9.3-p551@rails3.2/gems/rack-timeout-0.4.2/lib/rack/timeout/core.rb:66: Can't assign to nil
...alize(app, service_timeout:nil, wait_timeout:nil, wait_overt...
...                               ^
/Users/danolee/.rvm/gems/ruby-1.9.3-p551@rails3.2/gems/rack-timeout-0.4.2/lib/rack/timeout/core.rb:66: Can't assign to nil
..._timeout:nil, wait_timeout:nil, wait_overtime:nil, service_p...
...                               ^
/Users/danolee/.rvm/gems/ruby-1.9.3-p551@rails3.2/gems/rack-timeout-0.4.2/lib/rack/timeout/core.rb:66: Can't assign to nil
...timeout:nil, wait_overtime:nil, service_past_wait:false)
...                               ^
/Users/danolee/.rvm/gems/ruby-1.9.3-p551@rails3.2/gems/rack-timeout-0.4.2/lib/rack/timeout/core.rb:75: dynamic constant assignment
    RT = self # shorthand reference
        ^
/Users/danolee/.rvm/gems/ruby-1.9.3-p551@rails3.2/gems/rack-timeout-0.4.2/lib/rack/timeout/core.rb:147: dynamic constant assignment
    RX_NGINX_X_REQUEST_START  = /^(?:t=)?(\d+)\.(\d{3})$/
                               ^
/Users/danolee/.rvm/gems/ruby-1.9.3-p551@rails3.2/gems/rack-timeout-0.4.2/lib/rack/timeout/core.rb:148: dynamic constant assignment
    RX_HEROKU_X_REQUEST_START = /^(\d+)$/
                               ^
/Users/danolee/.rvm/gems/ruby-1.9.3-p551@rails3.2/gems/rack-timeout-0.4.2/lib/rack/timeout/core.rb:194: syntax error, unexpected keyword_end, expecting $end
	from /Users/danolee/.rvm/gems/ruby-1.9.3-p551@rails3.2/gems/rack-timeout-0.4.2/lib/rack/timeout/base.rb:1:in `<top (required)>'
	from /Users/danolee/.rvm/gems/ruby-1.9.3-p551@rails3.2/gems/rack-timeout-0.4.2/lib/rack-timeout.rb:1:in `require_relative'
	from /Users/danolee/.rvm/gems/ruby-1.9.3-p551@rails3.2/gems/rack-timeout-0.4.2/lib/rack-timeout.rb:1:in `<top (required)>'
	from /Users/danolee/.rvm/gems/ruby-1.9.3-p551@rails3.2/gems/bundler-1.12.4/lib/bundler/runtime.rb:86:in `require'
	from /Users/danolee/.rvm/gems/ruby-1.9.3-p551@rails3.2/gems/bundler-1.12.4/lib/bundler/runtime.rb:86:in `block (2 levels) in require'
	from /Users/danolee/.rvm/gems/ruby-1.9.3-p551@rails3.2/gems/bundler-1.12.4/lib/bundler/runtime.rb:81:in `each'
	from /Users/danolee/.rvm/gems/ruby-1.9.3-p551@rails3.2/gems/bundler-1.12.4/lib/bundler/runtime.rb:81:in `block in require'
	from /Users/danolee/.rvm/gems/ruby-1.9.3-p551@rails3.2/gems/bundler-1.12.4/lib/bundler/runtime.rb:70:in `each'
	from /Users/danolee/.rvm/gems/ruby-1.9.3-p551@rails3.2/gems/bundler-1.12.4/lib/bundler/runtime.rb:70:in `require'
	from /Users/danolee/.rvm/gems/ruby-1.9.3-p551@rails3.2/gems/bundler-1.12.4/lib/bundler.rb:102:in `require'
	from /Users/danolee/git/tp-dev-fresca/config/application.rb:7:in `<top (required)>'
	from /Users/danolee/.rvm/gems/ruby-1.9.3-p551@rails3.2/gems/railties-3.2.22.2/lib/rails/commands.rb:24:in `require'
	from /Users/danolee/.rvm/gems/ruby-1.9.3-p551@rails3.2/gems/railties-3.2.22.2/lib/rails/commands.rb:24:in `<top (required)>'
	from script/rails:6:in `require'
	from script/rails:6:in `<main>'`

Please help.

**Comment by radarek** [comment]
You are using ruby 1.9.3 which doesn't have keywords arguments and apparently rack-timeout use them. You have to upgrade your ruby version or stick with rack-timeout 0.3.2.

**Comment by wuputah** [comment]
https://www.ruby-lang.org/en/news/2014/01/10/ruby-1-9-3-will-end-on-2015/
