### ISSUE TITLE
timeout limit

### ISSUE THREAD

**Issue by linkinbr** [heroku/rack-timeout#111]
Hi there.

I need to know if there's any limit to the rack timeout value.

Here in my company we use nginx with ruby, and in the config.ru file the 
require "rack-timeout"
use Rack::Timeout
Rack::Timeout.timeout = 1800 # 30 min

is set.

The problem is by trying to set this value to 30min, 60min it gives me an error after 5 minutes of processing, like if the value set isn't allowed or recognized.

The following error shows up after 5 minutes:
Error code : -2 /  Message : Timeout::Error

Is there any limit, or even better, is there anyway to increase this value to 30, 60 minutes? We have some processes here that really take a LOT of time to finish and this timeout isn't working.

Thanks in advance!

**Comment by wuputah** [comment]
rack-timeout does not raise `Timeout::Error`, it raises `Rack::Timeout::RequestTimeoutError`. There is no maximum value.

I think your connection is timing out, anything more than 30 seconds is a very long time. You shouldn't do long processing like this in an HTTP request, use background jobs (e.g. sidekiq) instead.
