### ISSUE TITLE
Duplicate Pstatement Errors

### ISSUE THREAD

**Issue by tarr11** [heroku/rack-timeout#113]
According to this comment, `duplicate pstatement` errors are being caused by `rack-timeout` but I see no reference to that here.   The solution is to remove rack-timeout which would be unfortunate.  However, it is destabilizing to our heroku application.

Please advise if this is related to `rack-timeout`

https://github.com/rails/rails/issues/1627#issuecomment-76172622

**Comment by wuputah** [comment]
Yes, rack-timeout can interrupt your app at any time, and is a last resort debugging tool. It can cause issues with certain things, like database connections, ActiveRecord, etc.

Example of what you're seeing:
https://devcenter.heroku.com/articles/postgres-logs-errors#pgerror-prepared-statement-a30-already-exists

Pro tip: turn off ActiveRecord's prepared statements, we find they are more harmful than helpful (they use up Postgres memory but don't improve performance).
