### ISSUE TITLE
Recommended way to set the timeout 

### ISSUE THREAD

**Issue by mintuhouse** [heroku/rack-timeout#118]
[Documentation](https://github.com/heroku/rack-timeout#rails-apps) still used depreciated class methods to set the service_timeout value in rails apps.

Wanted to confirm if below code would be the recommended way to set it today?
````
# Gemfile
gem "rack-timeout", require:"rack/timeout/base"

# config/initializers/rack_timeout.rb
if defined?(ActionDispatch::RequestId)
  app.config.middleware.insert_after(ActionDispatch::RequestId, Rack::Timeout, service_timeout: 5)
else
  app.config.middleware.insert_before(Rack::Runtime, Rack::Timeout, service_timeout: 5)
end
````
It would be nice to have a simpler configuration option

**Comment by bobintornado** [comment]
yes i'd like to know this also.

and is gem still alive?

**Comment by bobintornado** [comment]
after reading the source code a bit I end up using 

`gem 'rack-timeout', require: 'rack/timeout/base'`

in the `Gemfile` and 

`config.middleware.insert_before Rack::Runtime, Rack::Timeout, service_timeout: 60 unless Rails.env.test?`

in `application.rb`.
