### ISSUE TITLE
Allow inserting middleware at arbitrary points in the middleware stack

### ISSUE THREAD

**Issue by osazemeu** [heroku/rack-timeout#120]
I want to Insert middleware before/after specific controllers methods or model methods in rails. I didn't find any use case for this in the docs or online. Can anyone show me how to do this?

**Comment by wuputah** [comment]
Middleware cannot be inserted on a per-controller / per-method / per-request basis. You need to 'wrap' the middleware in something that will conditionally enable it when desired.

This type of question is best asked on stackoverflow.com rather than Github issues.
