### ISSUE TITLE
undefined method `timeout=' for Rack::Timeout:Class (NoMethodError) for 0.5.0.1

### ISSUE THREAD

**Issue by thebravoman** [heroku/rack-timeout#130]
Updating from 
-    rack-timeout (0.4.2)
+    rack-timeout (0.5.0.1)

There is an error at 
````
# config/initializers/timeout.rb
Rack::Timeout.timeout = 30  # seconds
````

The error is
````
config/initializers/timeout.rb:2:in `<top (required)>': undefined method `timeout=' for Rack::Timeout:Class (NoMethodError)
````

Looked at the change log, but this breaking change was not mentioned? Is this expected as a breaking change between these two versions.

**Comment by wuputah** [comment]
Yes, this is one of the legacy class setters that was removed in this release.

**Comment by thebravoman** [comment]
What are we suppose to use instead? @wuputah

**Comment by thebravoman** [comment]
I suppose this - 
````
Rails.application.config.middleware.insert_before Rack::Runtime, Rack::Timeout, service_timeout: 5
````
It should have the same effect right?

**Comment by wuputah** [comment]
Yes, that works. Alternatively, you can use the environment variables (from #105).

**Comment by alorda** [comment]
> I suppose this -
> 
> ```
> Rails.application.config.middleware.insert_before Rack::Runtime, Rack::Timeout, service_timeout: 5
> ```
> 
> It should have the same effect right?

Where should this command be entered? In Heroku CLI?
