### ISSUE TITLE
Setting RACK_TIMEOUT_WAIT_TIMEOUT to false/0 on Heroku causes all requests to timeout

### ISSUE THREAD

**Issue by ozzyaaron** [heroku/rack-timeout#132]
We were previously using 0.4.x and setting `wait_timeout` to 0 via ENV variables and this worked to disable the wait timeout.

Upgrading to 0.5.x, removing the initializer and relying on RACK_TIMEOUT_WAIT_TIMEOUT set to 0 (I also tried false) then caused all of our requests to timeout as it seems to actually check against a 0 value for timeout. We then receive the following exception:

`<Rack::Timeout::RequestExpiryError: Request older than 0ms.>`

Setting RACK_TIMEOUT_SERVICE_TIMEOUT to 0/false appears to work as expected.

**Comment by wuputah** [comment]
0.5.1 has been released with the fix from #133. I was able to create both a test case in 748ef83, so should be all set, but let me know if you have any troubles.
