### ISSUE TITLE
Documentation: timing out requests without exiting is inherently unsafe

### ISSUE THREAD

**Issue by aripollak** [heroku/rack-timeout#39]
I ran into [this bug](https://github.com/rails/rails/issues/1627#issuecomment-31035002) rather frequently on a high traffic site with a somewhat high incidence of timeouts, using `Timeout.timeout`, very similarly to rack-timeout. It was happening almost daily - a request would time out and raise an exception at a place in ActiveRecord that left a model class in an unclean state; all subsequent requests in the same Unicorn worker that used the corrupted class would crash until the worker was restarted, and who knows what else was corrupted in there but wasn't raising an error.

I've taken to doing the following in an around_filter instead. This might be a good thing to do in rack-timeout, or at least have a note in the README about this possibility, since with enough timeouts you're bound to run into something like it sooner or later. Note that this code is not rescuing from `Timeout::Error` because if the timeout happens inside a Rails view, it will be caught and re-raised as a `ActionView::Template::Error`.

```ruby
  def exit_process_on_timeout(timeout, &block)
    # Ruby's Timeout can leave the process in a bad state since libraries tend
    # not to anticipate having an exception raised arbitrarily.
    # So we assume this process is corrupted and exit it after letting the request finish.
    Timeout.timeout timeout, Timeout::Error, &block
  rescue => e
    if e.message == 'execution expired'
      ::NewRelic::Agent.notice_error e, request: request
      ::NewRelic::Agent::Transaction.stop
      ::NewRelic::Agent.shutdown
      Process.kill 'QUIT', Process.pid
    end

    raise e
  end
```

**Comment by kch** [comment]
I guess I'm happy with the existing docs.

**Comment by dentarg** [comment]
Process kill/restart that was discussed here was implemented in https://github.com/sharpstone/rack-timeout/pull/157
