### ISSUE TITLE
Inflate rack-timeout log data

### ISSUE THREAD

**Issue by ryandotsmith** [heroku/rack-timeout#54]
Here is my problem:

I want to provide great customer service. When a customer sends my server a request, and for whatever reason the request is halted by the rack-timeout app, I would like to print the user portion of their basic authorization header in the rack-timeout log line. This way I can follow up with the customer to resolve any potential issues.

It was not immediately clear to me how I might go about this. Any suggestions?

**Comment by kch** [comment]
@ryandotsmith did you manage to implement what you wanted? Were the existing hooks sufficient?

Going to assume so and close this out, but let me know either way and please reopen if you feel something is missing that would help.
