### ISSUE TITLE
Consider adapting rubysl-timeout

### ISSUE THREAD

**Issue by evanphx** [heroku/rack-timeout#61]
Long ago, I rewrote timeout.rb so that it didn't require a 1-to-1 relationship between a thread and timeout thread. This meant that no matter the number of threads using timeouts, there was only one timeout thread. Given that rack-timeout uses that same 1-to-1 relationship, it is in danger of easily ballooning the number of threads used.

Here is the code for my timeout.rb you could adapt: https://github.com/rubysl/rubysl-timeout/blob/2.0/lib/rubysl/timeout/timeout.rb

You'd need remove the `Rubinius::Channel` stuff by using a ConditionVariable, but other than that, it should be easy to use.

**Comment by kch** [comment]
This is not a bad idea, but I wonder how much it's a problem in practice.

A thread only lives as long as request. A lot of ruby web apps are single-threaded, and even the threaded ones don't tend to use many threads.

Is creating and destroying threads expensive?

**Comment by evanphx** [comment]
@kch Creating threads is fairly expensive as far as operations go, yes. Another example is that people use rack-timeout with puma and I've seen people configure puma to use 2000 threads. Using rack-timeout in that case will result in an additional 2000 threads as well as constantly tearing down and creating new ones.

Since you only want the ability call `Thread.raise` after a time, using the single, persistent timer Thread has significant upsides.

**Comment by kch** [comment]
Fair enough. We'll do this. Might take me a while to get to it though.

**Comment by kch** [comment]
@evanphx you define `@mutex` and `@requests` but don't seem to use them?

**Comment by evanphx** [comment]
@kch Yeah, that's obviously dead code. But you'll have to adapt this to run on MRI anyway, that uses a `Rubinius::Channel` which you don't have to coordinate between the threads.

**Comment by kch** [comment]
@evanphx right. was just pointing those out to you.

**Comment by kch** [comment]
@evanphx in case you're curious, see #82

**Comment by kch** [comment]
Implemented in #82; will be in beta2, tracked via #78.
