### ISSUE TITLE
Disable time out for specific request

### ISSUE THREAD

**Issue by hamitturkukaya** [heroku/rack-timeout#64]
I have payment system in my application and sometimes bank request take too much time and application throws RequestTimeOutError. Is it possible to extend timeout for a specific requests or urls like in this comment http://stackoverflow.com/a/17574585/2232794

**Comment by dmathieu** [comment]
:-1: your request queue doesn't care where the request is coming from.
See #56 for more information.

**Comment by kch** [comment]
Specifically, see [this comment](https://github.com/heroku/rack-timeout/pull/56#issuecomment-61185025) where I address your situation exactly.
