### ISSUE TITLE
Per request timeout value ? 

### ISSUE THREAD

**Issue by rpechayr** [heroku/rack-timeout#67]
Hello, 

I was wondering if it was possible to set a different timeout per request ? For example I have a rails app with a `/api` namespace. I would like the timeout to be around 20 seconds for api requests. On the other hand, on all other requests I'd like it to be around 3 seconds. It this possible ? 

I am investigating thi gem because at the moment we're using unicorn a timeout are not really smartly handled since it involves killing the rails process  and forking another time whenever it happens. 

Thanks !

**Comment by kch** [comment]
This goes against the point of the library. There are a bunch of closed issues / PRs that allude to similar situations, and we've gone in detail in them explaining why it's a bad idea. Can't dig them up for you now, but shouldn't be too hard to find them.

**Comment by rpechayr** [comment]
Ok thanks. I'll check them up (max 66 issues to read ;)). I must have misunderstood something about *the point of this library*

**Comment by pickhardt** [comment]
Link for others:
https://github.com/heroku/rack-timeout/pull/56#issuecomment-61185025
