### ISSUE TITLE
Feature request: customizable error message

### ISSUE THREAD

**Issue by pickhardt** [heroku/rack-timeout#68]
Hi, I see you recently changed the error message to add more info. I think that's a step in the right direction, but it introduced a new problem. Specifically, for anyone that uses error tracking systems, they typically group the errors by name. So for example, the following are treated as different, even if they are both more or less the same:

a. Rack::Timeout::RequestTimeoutError: Request waited 21ms seconds, then ran for longer than 25000ms
b. Rack::Timeout::RequestTimeoutError: Request waited 22ms seconds, then ran for longer than 25000ms

I have two proposals that would avoid this:

1. Change the error message to round to the nearest second, so that you get things like:

a.  Rack::Timeout::RequestTimeoutError: Request waited less than 1 seconds, then ran for longer than 25s
b.  Rack::Timeout::RequestTimeoutError: Request waited 1 second, then ran for longer than 24s
c. Rack::Timeout::RequestTimeoutError: Request waited 20 seconds, then ran for longer than 5s

2. Let people define their own customizable method for how the error message should appear, with those waiting times as variables. Then when you call the error, use that (or the default).

Let me know what you think.

**Comment by dmathieu** [comment]
:-1: to losing preciseness because some tools have a problem. Fix your tools.

**Comment by pickhardt** [comment]
That's a bad rationale because that's how the tools work. Just add a method to let people customize it, then they can customize it to better integrate with error tracking tools. Yes, the tools should allow grouping, and they do, but their grouping algorithm isn't catching this for some reason.

**Comment by kch** [comment]
Can't you customise your system to group only on the exception class? The message is supposed to be informative.

I don't like the idea of changing it to accommodate an unnamed tool, but you can override `to_s` on our error classes to provide a static message.

**Comment by kch** [comment]
Which is to say, the functionality you want already exists as part of ruby. I understand people have come to fear what they call monkey-patching, but this hardly qualifies:

```ruby
class Rack::Timeout::Error
  def to_s
    "I hate details"
  end
end
```

(untested, could not do anything at all or set your computer on fire)

**Comment by tarr11** [comment]
We use Rollbar on heroku which creates bugs for our errors.  This issue is causing a large number of duplicate errors.    I do not believe I have an option to fix this in Rollbar.

**Comment by kch** [comment]
We use rollbar too. 

The problem is I don't think it's related to the error message as much as differing stack traces.

There are ways to make grouping rules in rollbar but they confuse me.

**Comment by neilmiddleton** [comment]
Personally, I don't see the benefit of adding `Request waited 21ms seconds` when you have the impact that people describe here.  As it's clear people use tools like Rollbar, maybe leave this detail to the logs which you'll be looking at when debugging the long running request.

This 'feature' seems to have more pain than gain.

**Comment by kch** [comment]
Yeah, I'll change this for the next release and we'll see how it goes. Again my suspicion is that different stack traces are more of a grouping problem for rollbar…

**Comment by kch** [comment]
FWIW, see _Exception Grouping_ in https://rollbar.com/docs/grouping-algorithm/

It looks like the exception message is not taken into account at all, but the stack trace matters. The problem is rack-timeout raises in the application thread at whatever point it happens to be in when the timeout happens, so you often get a different stack trace.

**Comment by kch** [comment]
For rollbar specifically, maybe rack-timeout could use custom fingerprinting based on the request url.

**Comment by kch** [comment]
@pickhardt, which system are you using btw?

**Comment by kch** [comment]
#88 attempts to address this for rollbar… 

feedback?

**Comment by kch** [comment]
The new rollbar module does what we need for rollbar.

 If the issue comes up with other error tracking systems please open a new issue.
