### ISSUE TITLE
Beta announcements

### ISSUE THREAD

**Issue by kch** [heroku/rack-timeout#78]
There doesn't seem to be a great way to do this in github, so I'll be announcing the next few betas here.

**Comment by mensfeld** [comment]
+1 - have the same issue ;)

**Comment by kch** [comment]
[`rack-timeout-0.3.0.pre.beta.1`](https://rubygems.org/gems/rack-timeout/versions/0.3.0.pre.beta.1) is out in rubygems.org.

Install: `gem install rack-timeout -v 0.3.0.pre.beta.1`

Gemfile: `gem "rack-timeout", "0.3.0.pre.beta.1"`

You'll need a recent version of rubygems that deals with the way I setup the version string. 
(`gem update --system`)

Feedback here or on the particular issues / PRs.

**Comment by watsonian** [comment]
@kch maybe Releases would work?

![2015-08-14 at 10 49 am](https://cloud.githubusercontent.com/assets/244/9277808/14796f30-4272-11e5-9116-bbac8705a164.png)

**Comment by kch** [comment]
Who sees that tho? Here people can subscribe, comment, etc.

Maybe I'll try one just for the hell of it.

**Comment by watsonian** [comment]
You could always have a announcements issue and then just link to new beta releases when they come out. *shrug*

**Comment by kch** [comment]
[`rack-timeout-0.3.0.pre.beta.2`](https://rubygems.org/gems/rack-timeout/versions/0.3.0.pre.beta.2) is out.

Install: `gem install rack-timeout -v 0.3.0.pre.beta.2`

Gemfile: `gem "rack-timeout", "0.3.0.pre.beta.2"`

This includes PR #82

**Comment by kch** [comment]
Unless there are objections I'm getting this out for GA by monday.

**Comment by kch** [comment]
0.3.0 is final 🎉

**Comment by daemonsy** [comment]
I was just looking at this issue and trying to decide whether to install `rack-timeout-puma` when the comment *0.3.0 is final  🎉* appeared live. The feeling is amazing and :clap: thanks!

**Comment by kch** [comment]
Work for 0.4.0 is underway. Beta 1 is tagged, although I'm not pushing it to rubygems for now.

To use it, pull from github in your `Gemfile`:

```ruby
gem "rack-timeout", github:"heroku/rack-timeout", tag:"v0.4.0-beta.1"
```

**Comment by kch** [comment]
0.4.0 is out
