### ISSUE TITLE
CircleCi issues

### ISSUE THREAD

**Issue by tbrammar** [heroku/rack-timeout#80]
Had `gem 'rack-timeout'` in my Gemfile as per the instructions. When I pushed to [CircleCi](https://circleci.com/) I was getting timeout issues etc.

Moving it into the production / staging block in my Gemfile fixed it:
````
group :staging, :production do
  gem 'rails_12factor'
  gem 'rack-timeout'
end
````
Config file dealt with as so:
````
# initializers/timeout.rb
unless Rails.env.development? || Rails.env.test?
  Rack::Timeout.timeout = 20  # seconds
end
````

You may want to add it to the instructions.

**Comment by scootklein** [comment]
+1 here. opening up a ticket with CircleCI

**Comment by jonyardley** [comment]
+1. Spent ages trying to figure out what the problem is without success

**Comment by ryanwood** [comment]
+1. FWIW, I simplified the initializer so I wouldn't have to configure the env twice:

```
# config/initializers/timeout.rb
if defined?(Rack::Timeout)
  Rack::Timeout.timeout = 20  # seconds
end
```

**Comment by kch** [comment]
Watch #78 for the next beta.
