### ISSUE TITLE
Is it possible to use a dynamic timeout value?

### ISSUE THREAD

**Issue by barbolo** [heroku/rack-timeout#95]
I've just posted the following question at SO and maybe you guys have an answer:

How to respond a Rails request within a configurable timeout
http://stackoverflow.com/questions/33193284/how-to-respond-a-rails-request-within-a-configurable-timeout

Thank you.

**Comment by Taytay** [comment]
I too would like to be able to set the timeout on a per-request basis. We have certain operations that we expect to take a long time to respond, and would like to capture that.

**Comment by vkinelev** [comment]
It looks like this does a trick:

```rb
# order_controller.rb

def some_long_action
  env[Rack::Timeout::ENV_INFO_KEY].timeout = 15
  ...
end
```

Can this way introduce an unexpected behaviour?

**Comment by kch** [comment]
@vkinelev I'm surprised that works to begin with, but yeah very likely to cause unexpected behaviour.

**Comment by kch** [comment]
There are past issues here about having custom timeouts, so do a bit of search. We explain why it's a bad idea in a few comments. 

Basically, any slow request will cause a bunch of other would-be fast ones to suffer. So handle that stuff async.

**Comment by vkinelev** [comment]
@kch Thank you for the response!

I understand the problem and in most of cases we either optimise performance or/and move slow things into DelayedJob. But for that one particular endpoint we have to do really a lot to optimise it. So I just was hoping to quickly increase timeout and then do an actual performance optimisation.

**Comment by kch** [comment]
Pretty sure there are forks by others out there that offer this feature. It's not too hard to implement, I just prefer to not support it out of the box. Don't wanna make it too easy for people to take the wrong path.
