### ISSUE TITLE
Rollbar fingerprinting not very useful as it is (at least for Rails apps)

### ISSUE THREAD

**Issue by oboxodo** [heroku/rack-timeout#97]
I just upgraded to latest rack-timeout and was glad to find the new rollbar module. But it's not being as useful as expected.

I think the main issue is [using the fullpath](https://github.com/heroku/rack-timeout/blob/master/lib/rack/timeout/rollbar.rb#L30) as part of the fingerprinting process.

In our specific case, we're using Rails and I'd expect timeouts with the following `fullpath`s to be grouped because they all are routed to the same controller + action:

"posts" controller, "show" action:
* /posts/1
* /posts/2

"search" controller, "show" action:
* /search?q=foo
* /search?q=bar

So I think that, in the case of Rails applications, it might be better to use the routed `controller` + `action` instead of the full path. I really didn't take the time to think deep about that information being present at the time all timeouts might get raised, etc. But at least we could use those if they are, and fallback to the fullpath if they're not?

I'm aware this might be too Rails specific. But I wanted to raise the issue anyway.

If you don't want to hard-code a fingerprinting algorithm to satisfy everyone... then maybe you could provide a configuration hook in order for the app's developer to provide a lambda to customize it?

**Comment by kch** [comment]
I added the mechanism for a custom fingerprint; if you come up with a nice one for rails please share and I'll see if it makes sense to integrate it.

**Comment by theinventor** [comment]
@kch for those rails shops that want to go with the default rollbar grouping stuff, we just include right?

No other configuration?

**Comment by kch** [comment]
@theinventor yeah, the default thing remains the same, just require the file.
